import './global.css';
import { ServicesProvider } from '@journey-orchestrator/services';

export const metadata = {
  title: 'Welcome to journey-orchestrator',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  wizard,
  children,
}: {
  wizard: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ServicesProvider>
          {children}
          {wizard}
        </ServicesProvider>
      </body>
    </html>
  );
}
